title: Kaulik Makwana
description: |
  Offensive Security Engineer & Penetration Tester
  Specializing in ethical hacking and securing digital infrastructure through advanced techniques.
author:
  name: Kaulik Makwana
  bio: |
    Cybersecurity Engineer:
    - Work in offensive security, with a primary focus on ethical hacking and securing digital infrastructure through advanced techniques.
    
    Penetration Tester:
    - Core expertise lies in simulating real-world attacks, identifying vulnerabilities, and assessing the security posture of systems and networks.

baseurl: ""
url: "https://kaulikmakwana.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Use existing writeups folder
collections:
  writeups:
    output: true
    permalink: /writeups/:path/
    source: writeups/content

defaults:
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
