# Add these configurations to your existing _config.yml
collections:
  writeups:
    output: true
    permalink: /writeups/:title/

defaults:
  - scope:
      path: ""
      type: "writeups"
    values:
      layout: "writeup"
